# Generated by Django 3.2 on 2021-06-01 22:23

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=64)),
                ('keywords', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='SearchWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_word', models.CharField(max_length=64)),
                ('keywords', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'db_table': 'searchword',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('contents', models.TextField()),
                ('url', models.URLField()),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('vectors', picklefield.fields.PickledObjectField(blank=True, editable=False, null=True)),
                ('similarity', models.FloatField(blank=True, null=True)),
                ('top_keywords', picklefield.fields.PickledObjectField(blank=True, editable=False, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawling.category')),
                ('search_word', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crawling.searchword')),
            ],
            options={
                'db_table': 'article',
            },
        ),
    ]
