# Generated by Django 3.2 on 2021-06-03 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='similarity',
        ),
        migrations.RemoveField(
            model_name='article',
            name='vectors',
        ),
    ]
