# Generated by Django 3.2 on 2021-06-04 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0002_auto_20210603_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='search_word',
        ),
        migrations.DeleteModel(
            name='SearchWord',
        ),
    ]
