# Generated by Django 3.2 on 2021-06-04 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0004_category_topics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='top_keywords',
        ),
    ]
