# Generated by Django 3.2.4 on 2021-06-05 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0006_auto_20210605_1546'),
        ('crawling', '0007_alter_article_id'),
    ]

    operations = [
    ]
